[build]
    command = "npm run build"
    functions = "functions"
    publish = "dist/blog-client"

   [[redirects]]
      from = "https://modest-bhabha-3a9de8.netlify.app/*"
      to = "https://modest-bhabha-3a9de8.netlify.app"
      status = 200